name: C++ CI Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile Application
      run: g++ -O2 main.cpp -o program

    - name: Run Automated Tests
      run: ./program
